### PR TITLE
Fix arrow dependency

### PR DESCRIPTION
**Pull request by Garra1980**
Looks like 5.8 supports Arrow5

cc @pearu

### CODE REVIEW

**Comment by andrewseidl** [comment]
Looks like it's complaining about

```
-   - nothing provides arrow-cpp-proc 5.* cuda needed by omniscidbe-5.8.0-h1234567_0_cuda
```

**Comment by Garra1980** [comment]
Indeed I don't see 5.0.0 packages for linux-64 here https://anaconda.org/conda-forge/arrow-cpp/files

**Comment by pearu** [comment]
There is: https://anaconda.org/conda-forge/arrow-cpp/5.0.0/download/linux-64/arrow-cpp-5.0.0-py39h67699a3_11_cuda.tar.bz2

Notice that in arrow-cpp 5, the version of arrow-cpp-proc is 3.

**Comment by Garra1980** [comment]
Right, right, let me try with that version of arrow-cpp-proc

**Comment by Garra1980** [comment]
CI is green! @pearu @andrewseidl pls take a look

**Review by pearu — APPROVED** [review]
LGMT! Thanks @Garra1980 !

**Comment by vnlitvinov** [comment]
This PR is incorrect, it doesn't bump build number.
It won't appear on conda-forge.

**Comment by pearu** [comment]
Here's a follow-up to fix the build number: #64

**Comment by Garra1980** [comment]
Thanks!

**Pull request merged**
