### PR TITLE
OmniSci 5.5 Updates

### PR DESCRIPTION
**Pull request by jclay**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jclay** [comment]
@conda-forge-admin, please rerender

**Comment by jclay** [comment]
@conda-forge-admin, please rerender

**Comment by jclay** [comment]
@pearu any thoughts on this? I can updated it to make the changes mentioned in #24

**Comment by pearu** [comment]
@jclay in general, it looks good. I haven't tested it locally though and so I don't have detailed feedback yet.

I think this PR cannot be merged until omniscidb 5.5 is released. Conda packaging omniscidb master branch could be done but using some dev channel.

**Comment by pearu** [comment]
Closing via #26 and #28

**Pull request closed without merging**
