### PR TITLE
Include `cdt_name` to pickup CDT's matching OS

### PR DESCRIPTION
**Pull request by jakirkham**
Ensure `cdt_name` is included to pull in CDTs matching the OS as discussed in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/867 ).

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pearu** [comment]
The CI fails because omniscidb 5.4 is not LLVM 11 ready.

**Comment by jakirkham** [comment]
How should that be addressed?

**Comment by pearu** [comment]
> How should that be addressed?

Most likely by updating meta.yaml as follows:
```
  - llvmdev<11
  - clangdev<11
  - llvm<11
```
There is another issue with `clang-cpp`: run is currently using v 11 while it should use the same as was used in build (that is 10). Perhaps this needs to be addressed in a different PR.. I can look into it tomorrow..

**Comment by pearu** [comment]
https://github.com/conda-forge/omniscidb-feedstock/pull/19 will resolve the build failure.

**Comment by pearu** [comment]
@jakirkham , rebase should fix the build failures.

**Comment by jakirkham** [comment]
Thanks! 😄 Have fixed merge conflicts.

**Pull request merged**
